device: 'cuda'
train:
  batch_size: 32
  epochs: 100
  num_workers: 1`
  optimizer:
    type: 'AdamW'
    params:
      lr: 0.001
      weight_decay: 0.0
  loss:
    type: 'CE'
  save_interval: 20
  val_interval: 1
  checkpoint_dir: 
test:
  batch_size: 64
  num_workers: 1
  checkpoint_dir: './output/checkpoint_best.pth'
model:
  type: 'resnet'
  input_size: [32, 32]
  num_classes: 10
  pretrained: True
  dropout_rate: 0
seed: 42
data:
  train_images_path: './data/train_images.npy'
  train_labels_path: './data/train_labels.npy'
  val_images_path: './data/val_images.npy'
  val_labels_path: './data/val_labels.npy'
  test_images_path: './data/test_images.npy'
  filter: True
output_dir: '.'